language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd build
- docker-compose build orocommerce
- docker-compose up -d
- docker-compose ps
- cd $TRAVIS_BUILD_DIR
before_script:
- pip install requests
- pip install docker
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd build
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose -f images
- docker push trydirect/orocommerce:3.1
