version: '2'

volumes:
    orocommerce-db:
      driver: local

services:
  orocommerce-de:
    image: ${REGISTRY}trydirect/orocommerce:1.6.13
    container_name: orocommerce-de
    hostname: orocommerce-de
    user: root
    restart: always
    ports:
          - "443:443"
          - "80:80"
    volumes:
        - ./project:${DOCROOT}
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./certs/letsencrypt:/etc/letsencrypt
        - ./certs/ssl:/etc/nginx/ssl
        - ./cron:/var/spool/cron/crontabs
    links:
        - db
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
    working_dir: /home/orocommerce

  db:
    image: mysql:5.7
    container_name: orocommerce_db
    restart: always
    volumes:
        - orocommerce-db:/var/lib/mysql
    env_file:
      .env
