version: '2'

volumes:
    orocommerce-db:
      driver: local

services:
  orocommerce-de:
    image: ${REGISTRY}trydirect/orocommerce:1.6.13
    container_name: orocommerce-de
    hostname: orocommerce-de
    user: root
    restart: always
    ports:
          - "443:443"
          - "80:80"
    volumes:
        - ./project:${DOCROOT}
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./certs/letsencrypt:/etc/letsencrypt
        - ./certs/ssl:/etc/nginx/ssl
        - ./cron:/var/spool/cron/crontabs
    links:
        - db
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
    working_dir: /home/orocommerce

  db:
    image: mysql:5.7
    container_name: orocommerce_db
    restart: always
    volumes:
        - orocommerce-db:/var/lib/mysql
    env_file:
      .env

  agent:
    image: ${REGISTRY}trydirect/status
    container_name: trydirect_agent
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/app/destination_conf
      - ./nginx_original:/app/origin_conf
      - ./config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NGINX_CONTAINER=orocommerce-de
      - STATUS_PANEL_USERNAME=admin
      - STATUS_PANEL_PASSWORD=${MYSQL_PASSWORD}